// AUTO-GENERATED from _content-integration/exploration-content-demo-roles-V1.md
// Exploration-layer DETAIL content for the 6 original demo roles (which already
// exist as cards in CAREERS). Keyed by existing slug. Prose verbatim from source.
// Regenerate via _content-integration/generate-demo-roles.mjs.
import type { CareerDetailContent } from '../careerDetail'

export const DEMO_ROLE_DETAIL: Record<string, CareerDetailContent> = {
  "software-engineer": {
    aboutRole: ["Software engineers design, build, test, and maintain the systems that run modern life: web and mobile apps, backend services, data pipelines, and the infrastructure underneath them. The job is less about typing code in isolation and more about solving problems: translating a fuzzy product requirement into a working, reliable system, then keeping it running as it scales. Most engineers specialize over time (frontend, backend, full-stack, mobile, infrastructure, or machine learning), but the core skill is the same everywhere: breaking a hard problem into pieces a computer can execute, and collaborating with other engineers to assemble those pieces into something dependable. It is among the highest-paying and most flexible entry points for technically minded graduates, with strong remote options and demand across nearly every industry, since almost every company is now a software company to some degree."],
    typicalWorkday: ["Morning: stand-up with the team, then pick up a ticket and read through the relevant part of the codebase. Midday: write and test code for a new feature, open a pull request, and respond to review comments from teammates. Afternoon: debug a production issue flagged overnight, pair with another engineer on a tricky bug, and review a colleague's pull request before logging changes for tomorrow."],
    aiImpact: ["This is one of the roles most actively reshaped by AI. Coding assistants can generate, explain, and debug code, shifting the junior workflow from writing every line to directing, reviewing, and integrating AI-generated output. The mechanical parts of coding are getting faster; the judgment parts (system design, knowing what to build, debugging subtle failures, owning reliability) are becoming the differentiators. Demand remains strong overall, but the role increasingly favors engineers who wield AI tools well and operate at the design-and-judgment level rather than pure code production."],
    requiredSkills: ["Proficiency in one or more programming languages (Python, JavaScript/TypeScript, Java, Go)","data structures and algorithms","version control with Git","debugging and testing","reading and navigating large existing codebases","system design fundamentals","collaboration through code review","increasingly, fluency directing AI coding assistants"],
    education: { majors: ["Computer Science","Software Engineering","Computer Engineering"], graduateDegrees: ["not required; a master's or PhD matters mainly for specialized fields like machine learning or research"] },
    sampleCompanies: ["Google, Microsoft, Amazon, Meta, Apple, plus thousands of startups and nearly every large non-tech company with software teams (banks, retailers, healthcare systems, government)"],
  },
  "marketing-manager": {
    aboutRole: ["Marketing managers own how a product or brand reaches and persuades its audience. They sit at the intersection of creativity and analytics: shaping the message and the campaigns that carry it, then measuring what actually moves customers to act. The role spans a wide range depending on the company: brand marketing (building awareness and identity), product marketing (positioning a product and arming sales), growth and performance marketing (running paid channels and optimizing conversion), and content or lifecycle marketing. A marketing manager typically owns a budget, a set of channels, and a number to hit, coordinating designers, writers, agencies, and analysts to hit it. It is one of the most common paths for creative-but-commercial graduates, and one of the few business roles judged on both taste and measurable results."],
    typicalWorkday: ["Morning: review last week's campaign performance and shift budget across channels toward what is converting. Midday: meet with designers and writers to shape creative for an upcoming launch, then brief an agency on a paid campaign. Afternoon: build a slide for leadership on the quarter's pipeline contribution, and draft messaging for a new feature announcement."],
    aiImpact: ["AI is rapidly changing the production side of marketing: drafting copy, generating creative variations, analyzing campaign data, and personalizing content at scale. This compresses time spent on execution and shifts the role toward strategy, brand judgment, and knowing which message will actually resonate, things AI cannot reliably decide. Performance and growth roles that pair creativity with strong analytics are in steady demand; purely execution-focused roles are more exposed. The managers who advance use AI to move faster while owning the taste and strategy that distinguish a brand."],
    requiredSkills: ["Clear writing and messaging","understanding of customer psychology and segmentation","comfort with marketing analytics and channel metrics","project management across creative and cross-functional teams","familiarity with tools like Google Analytics, a CRM, and ad platforms","storytelling","increasingly, using AI tools for content drafting and campaign analysis"],
    education: { majors: ["Marketing","Business","Communications","English","Psychology"], graduateDegrees: ["not required; some pursue an MBA to move into senior brand or strategy roles"] },
    sampleCompanies: ["Consumer brands (Nike, Procter & Gamble, Coca-Cola), tech companies (every SaaS firm has product and growth marketing), agencies (Ogilvy, Wieden+Kennedy), and essentially every company that sells something"],
  },
  "financial-analyst": {
    aboutRole: ["Financial analysts turn numbers into decisions. They build financial models, analyze performance, forecast future results, and recommend where money should go, whether that is inside a company (corporate finance, evaluating projects and budgets) or at an investment firm (analyzing securities and markets). The title is a broad entry point into finance: it covers corporate analysts who support business decisions, equity and credit analysts who evaluate investments, and analysts at banks and funds. The common thread is rigor with numbers and the ability to explain what they mean to the people making decisions. It is one of the most accessible finance roles for quantitatively minded graduates and a strong launching pad toward investment banking, corporate finance leadership, FP&A, or investment management."],
    typicalWorkday: ["Morning: update a financial model with the latest actuals and investigate a variance from forecast. Midday: build an analysis comparing two potential investments or projects, and meet with a business partner to understand the assumptions behind their request. Afternoon: prepare a summary memo or slides explaining your recommendation, and reconcile your numbers against the accounting close."],
    aiImpact: ["AI is automating much of the mechanical analysis: pulling data, building first-draft models, generating variance commentary, and summarizing reports. This shifts the role toward interpretation, judgment, and communicating with decision-makers, the parts that require business context AI lacks. Demand stays steady because every company and investor needs financial analysis. The routine reporting end of the role is more exposed than the judgment-heavy investment and business-partnering end, and the analysts who advance pair modeling skill with the ability to translate numbers into a recommendation a leader can act on."],
    requiredSkills: ["Financial modeling and Excel","understanding of financial statements","valuation and forecasting","analytical and critical thinking","clear written and verbal communication of findings","attention to detail","increasingly, data tools like SQL and BI platforms, plus AI for first-draft analysis"],
    education: { majors: ["Finance","Accounting","Economics","Business","Mathematics"], graduateDegrees: ["not required to start; the CFA designation and an MBA are common for advancement, especially on the investment side"] },
    sampleCompanies: ["Investment banks and asset managers (JPMorgan, Goldman Sachs, BlackRock, Fidelity), and the corporate finance teams of nearly every large company (Microsoft, Disney, PepsiCo, United Airlines)"],
  },
  "data-scientist": {
    aboutRole: ["Data scientists extract insight and build predictive systems from data. They sit between statistics, programming, and business: framing a question (why are customers churning, what will demand look like next quarter, which users should see which content), then using data, statistical methods, and increasingly machine learning to answer it and put that answer into production. The role ranges from analytics-focused work (understanding what happened and why, to inform decisions) to machine-learning-focused work (building models that make predictions or power product features). Strong data scientists are distinguished less by exotic algorithms than by asking the right question, working with messy real-world data, and communicating findings clearly enough to change a decision. It is among the most in-demand and well-paid technical roles for quantitatively minded graduates."],
    typicalWorkday: ["Morning: pull and clean a dataset, then explore it to understand a churn pattern the product team flagged. Midday: build and validate a model, run an experiment analysis, and discuss results with engineers and product managers. Afternoon: build a clear visualization and write up the finding for stakeholders, then collaborate with engineering to put a model into production."],
    aiImpact: ["Data science sits close to the AI wave and is being reshaped on both sides: AI tools accelerate the coding, cleaning, and exploratory work, while demand grows for people who can build, evaluate, and deploy machine learning and AI systems responsibly. The routine reporting and dashboarding end of the field overlaps with analyst roles and is more automatable; the modeling, experimentation, and ML-engineering end is in strong demand. The data scientists who thrive pair statistical and ML depth with business judgment and the ability to communicate uncertainty honestly."],
    requiredSkills: ["Programming in Python or R","SQL and working with databases","statistics and experimental design (A/B testing)","machine learning fundamentals","data cleaning and wrangling","data visualization and communication","translating business questions into analyses","increasingly, using and evaluating AI and large-language-model tools as part of the workflow"],
    education: { majors: ["Statistics","Computer Science","Mathematics","Economics","Data Science","Physics","Engineering"], graduateDegrees: ["a master's or PhD is common and sometimes expected for research-heavy or machine-learning roles, though strong analytics roles are open to bachelor's holders"] },
    sampleCompanies: ["Tech companies (Google, Meta, Netflix, Amazon, Microsoft), plus data teams across finance, healthcare, retail, and consulting; nearly every large company now has a data science function"],
  },
  "ux-designer": {
    aboutRole: ["UX (user experience) designers shape how a product feels to use. They research what users need, design the flows and interfaces that meet those needs, and test whether the result actually works, before and during engineering build. The role blends empathy, research, and craft: a UX designer might run user interviews, map a journey, sketch and prototype screens, and partner closely with product managers and engineers to ship something intuitive. Related titles include product designer (often broader, spanning research through visual design), UX researcher (focused on understanding users), and UI designer (focused on the visual interface). Good UX work is often invisible: when a product feels obvious and effortless, a designer made deliberate choices to make it so. It is one of the most accessible creative-yet-analytical paths into the technology industry."],
    typicalWorkday: ["Morning: synthesize notes from yesterday's user interviews and update a journey map. Midday: design and prototype several versions of a new flow in Figma, then review them with a product manager and engineer for feasibility. Afternoon: run a quick usability test, incorporate feedback, and present design options to the team, defending the reasoning behind your choices."],
    aiImpact: ["AI is accelerating parts of design: generating layout options, drafting copy, summarizing research, and producing quick prototypes, which shifts the designer's value toward judgment, user empathy, and the harder problems of what to build and why. Routine interface production is more exposed; the research, strategy, and systems-thinking end of UX is more durable. Demand remains solid as software proliferates, and the designers who advance pair craft with the ability to understand users deeply and influence product direction, not just produce screens."],
    requiredSkills: ["Design tools like Figma","wireframing and prototyping","user research and usability testing","visual and interaction design fundamentals","understanding of user psychology and accessibility","communicating and defending design decisions","collaboration with product and engineering","increasingly, using AI tools to accelerate prototyping and research synthesis"],
    education: { majors: ["Design","Human-Computer Interaction","Psychology","Cognitive Science","Fine Arts"], graduateDegrees: ["not required; a strong portfolio matters far more than a degree"] },
    sampleCompanies: ["Tech companies (Apple, Google, Airbnb, Spotify, Adobe), design-forward startups, agencies (IDEO), and the growing in-house design teams at banks, retailers, and healthcare companies"],
  },
  "sales-representative": {
    aboutRole: ["Sales representatives are the revenue engine of most companies: they find potential customers, understand their needs, and persuade them to buy. The role spans a wide spectrum, from inside sales and sales development (often the entry point, prospecting and qualifying leads), to account executives who own deals end to end, to enterprise reps who manage long, complex sales to large organizations. Modern selling, especially in business-to-business and software (SaaS), is less about the hard pitch and more about consultative problem-solving: diagnosing what a customer actually needs and showing how your product solves it. It is one of the most accessible and meritocratic entry points into business, where performance is measured clearly and strong performers can earn well early through commission, with a direct path into account management, sales leadership, or customer success."],
    typicalWorkday: ["Morning: research and prospect new accounts, then send personalized outreach and follow-ups. Midday: run discovery calls and product demos, listening for the customer's real needs and tailoring the pitch. Afternoon: update the CRM, advance deals through the pipeline, prepare a proposal, and coordinate with sales engineering or leadership on a larger opportunity."],
    aiImpact: ["AI is transforming the mechanics of sales: drafting outreach, researching prospects, transcribing and analyzing calls, and prioritizing leads. This automates much of the administrative grind and shifts the rep's value toward the human core of selling, building trust, navigating complex stakeholders, and consultative problem-solving, which remains hard to automate. Transactional, high-volume selling is more exposed; complex and relationship-driven sales are more durable. Demand stays strong because companies always need revenue, and the reps who thrive pair genuine relationship skills with the discipline to use AI tools to sell more efficiently."],
    requiredSkills: ["Communication and active listening","relationship-building and persuasion","resilience and handling rejection","understanding customer needs and qualifying fit","managing a pipeline and following a process","comfort with a CRM like Salesforce","negotiation","increasingly, using AI tools for research, outreach, and call analysis"],
    education: { majors: ["open to nearly any field; Business, Communications, and Marketing are common, though many successful reps come from unrelated backgrounds"], graduateDegrees: ["not required; results and track record matter far more"] },
    sampleCompanies: ["SaaS and tech companies (Salesforce, Oracle, HubSpot, ServiceNow), plus sales forces across pharmaceuticals, financial services, manufacturing, media, and consumer goods"],
  },
}
